CREATE TABLE Authors (
AuthorID int,
AuthorName varchar(20),
BirthDate Date,
PRIMARY Key(AuthorID));

CREATE TABLE BOOKS (
   BOOKID int, 
	TITLE VARCHAR2(20 ), 
	GENRE VARCHAR2(15), 
	AUTHORID int,
    PRIMARY KEY(BOOKID),
    FOREIGN KEY(AUTHORID) REFERENCES AUTHORS(AuthorID));
   
 CREATE TABLE BORROWERS  (
 BORROWERID int, 
	BORROWERNAME VARCHAR2(20), 
	CONTACTINFO VARCHAR2(20)
    PRIMARY Key (BORROWERID));
    
  CREATE TABLE LOANS (
  LOANID int, 
	BOOKID int, 
	BORROWERID int, 
	LOANDATE DATE, 
	RETURNDATE DATE, 
	AUTHORERID int(2),
    PRIMARY KEY(LOANID),
    FOREIGN KEY(BORROWERID) REFERENCES BORROWERS(BORROWERID));
    FOREIGN KEY(AUTHORERID) REFERENCES AUTHORS(AUTHORID));
   
    